import type { Game } from "@/types/domain";

const createdAt = "2026-06-01T12:00:00.000Z";

export const mockGames: Game[] = [
  {
    id: "shadow-of-the-colossus",
    title: "Shadow of the Colossus",
    platform: "PS2",
    filePath: "D:/Games/PS2/Shadow of the Colossus.iso",
    fileName: "Shadow of the Colossus.iso",
    fileExtension: ".iso",
    coverLocalPath: "/covers/shadow.svg",
    description:
      "Em uma terra proibida e silenciosa, um jovem enfrenta criaturas monumentais para tentar restaurar uma vida perdida.",
    releaseYear: 2005,
    genre: "Ação e aventura",
    region: "NTSC-U",
    serial: "SCUS-97472",
    lastPlayedAt: "2026-06-30T21:42:00.000Z",
    playtimeSeconds: 68400,
    isFavorite: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "god-of-war-ii",
    title: "God of War II",
    platform: "PS2",
    filePath: "D:/Games/PS2/God of War II.chd",
    fileName: "God of War II.chd",
    fileExtension: ".chd",
    coverLocalPath: "/covers/war.svg",
    description:
      "Kratos desafia os deuses em uma jornada brutal através da mitologia grega para alterar o próprio destino.",
    releaseYear: 2007,
    genre: "Hack and slash",
    region: "NTSC-U",
    serial: "SCUS-97481",
    lastPlayedAt: "2026-06-28T19:10:00.000Z",
    playtimeSeconds: 33120,
    isFavorite: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "gran-turismo-4",
    title: "Gran Turismo 4",
    platform: "PS2",
    filePath: "D:/Games/PS2/Gran Turismo 4.iso",
    fileName: "Gran Turismo 4.iso",
    fileExtension: ".iso",
    coverLocalPath: "/covers/velocity.svg",
    description:
      "Uma celebração do automobilismo com centenas de carros, circuitos precisos e uma carreira profunda.",
    releaseYear: 2004,
    genre: "Corrida",
    region: "PAL",
    serial: "SCES-51719",
    playtimeSeconds: 112800,
    isFavorite: false,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "persona-4",
    title: "Persona 4",
    platform: "PS2",
    filePath: "D:/Games/PS2/Persona 4.iso",
    fileName: "Persona 4.iso",
    fileExtension: ".iso",
    coverLocalPath: "/covers/midnight.svg",
    description:
      "Mistério, amizade e batalhas sobrenaturais se encontram em uma pequena cidade japonesa tomada por estranhos assassinatos.",
    releaseYear: 2008,
    genre: "RPG",
    region: "NTSC-U",
    serial: "SLUS-21782",
    lastPlayedAt: "2026-06-22T23:05:00.000Z",
    playtimeSeconds: 172500,
    isFavorite: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "metal-gear-solid-3",
    title: "Metal Gear Solid 3",
    platform: "PS2",
    filePath: "D:/Games/PS2/Metal Gear Solid 3 Subsistence.iso",
    fileName: "Metal Gear Solid 3 Subsistence.iso",
    fileExtension: ".iso",
    coverLocalPath: "/covers/snake.svg",
    description:
      "Espionagem tática em território hostil durante a Guerra Fria, onde sobrevivência e lealdade entram em conflito.",
    releaseYear: 2006,
    genre: "Ação furtiva",
    region: "NTSC-U",
    serial: "SLUS-21243",
    playtimeSeconds: 45900,
    isFavorite: false,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "okami",
    title: "Ōkami",
    platform: "PS2",
    filePath: "D:/Games/PS2/Okami.chd",
    fileName: "Okami.chd",
    fileExtension: ".chd",
    coverLocalPath: "/covers/okami.svg",
    description:
      "A deusa Amaterasu restaura a vida e as cores do Japão clássico usando um pincel celestial.",
    releaseYear: 2006,
    genre: "Ação e aventura",
    region: "NTSC-U",
    serial: "SLUS-21115",
    playtimeSeconds: 24600,
    isFavorite: false,
    createdAt,
    updatedAt: createdAt,
  },
];
